on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Apertium Core
        run: |
          wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
          sudo apt-get -f install apertium-all-dev

      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '7.7'

      - name: Build documentation
        run: |
          ./autogen.sh
          make docs
        shell: bash

      - name: Deploy on Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: docs
